name: scanneranimal
description: "IA Veterinaria - Diagnóstico, Gestación y Seguimiento"
publish_to: 'none'

version: 1.0.24+27 

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- AUTENTICACIÓN ---
  google_sign_in: ^6.2.1

  # --- MULTIMEDIA Y VIDEO ---
  video_player: ^2.8.1

  # --- HARDWARE Y SENSORES ---
  # ACTUALIZADO: La versión 4.1.1 ya no tiene el error de toLowerCase
  nfc_manager: ^4.1.1
  vibration: ^1.9.0

  # --- NAVEGACIÓN Y ESTADO ---
  go_router: ^13.1.0
  provider: ^6.1.1

  # --- BACKEND Y CLOUD ---
  firebase_core: ^4.5.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # --- INTELIGENCIA ARTIFICIAL ---
  # ACTUALIZADO: Reemplazamos la librería descontinuada
  firebase_ai: ^3.9.0

  # --- SISTEMA DE PAGOS ---
  in_app_purchase: ^3.2.0

  # --- NOTIFICACIONES Y UPDATES ---
  awesome_notifications: ^0.11.0 
  in_app_update: ^4.2.1

  # --- CALIFICACIÓN Y MEMORIA ---
  in_app_review: ^2.0.9
  shared_preferences: ^2.2.2

  # --- GENERACIÓN DE PDF Y REPORTES ---
  pdf: ^3.10.8
  printing: ^5.11.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Resolvemos conflictos de versiones de paquetes internos
dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/video/

flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "assets/icons/logo_app.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icons/logo_app.png"