buildscript {
    // CORRECCIÓN DEFINITIVA: 1.9.22 es perfecta para el SDK 36 y nfc_manager
    ext.kotlin_version = '1.9.22' 
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // ACTUALIZACIÓN: Subimos a 8.2.1 para soportar mejor el SDK 36
        // Esta versión de Gradle es necesaria cuando compileSdk es 35 o 36
        classpath 'com.android.tools.build:gradle:8.2.1' 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

// Bloque de carga de llaves para el firmado en producción
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}