buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                // Parche de Namespaces para Firebase y Notifications
                if (namespace == null || namespace.isEmpty()) {
                    def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
                    if (manifestFile.exists()) {
                        def manifestXml = new XmlParser().parse(manifestFile)
                        def packageName = manifestXml.attribute('package')
                        if (packageName != null) { namespace = packageName }
                    }
                }
                compileSdk = 34
                buildToolsVersion = "34.0.0"

                // Forzamos Java 11 para evitar conflictos con in_app_review
                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_11
                    targetCompatibility = JavaVersion.VERSION_11
                }
            }
        }

        // Parche de silencio para Kotlin (Fundamental para nfc_manager)
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            kotlinOptions {
                jvmTarget = "11"
                allWarningsAsErrors = false
                freeCompilerArgs += [
                    "-Xskip-prerelease-check",
                    "-nowarn",
                    "-Xsuppress-version-warnings",
                    "-Xallow-unstable-dependencies"
                ]
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}