// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8nWd7wFqR8mdPJwEqrUYHiyqSN1ijNY',
    appId: '1:71382402825:web:95402b132c675faf79f5d8',
    messagingSenderId: '71382402825',
    projectId: 'howudghzrpiiq92yrznw1kuorjca2t',
    authDomain: 'howudghzrpiiq92yrznw1kuorjca2t.firebaseapp.com',
    storageBucket: 'howudghzrpiiq92yrznw1kuorjca2t.firebasestorage.app',
    measurementId: 'G-R55JNVNBYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPXtnD2li6aO_sl3H41Trc0tZZI4EJrgg',
    appId: '1:71382402825:android:780945820c0ffcfd79f5d8',
    messagingSenderId: '71382402825',
    projectId: 'howudghzrpiiq92yrznw1kuorjca2t',
    storageBucket: 'howudghzrpiiq92yrznw1kuorjca2t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnfJfQb9DIUVLLfbe4eBYim52UJlj6RA',
    appId: '1:71382402825:ios:3eb214d6047de00279f5d8',
    messagingSenderId: '71382402825',
    projectId: 'howudghzrpiiq92yrznw1kuorjca2t',
    storageBucket: 'howudghzrpiiq92yrznw1kuorjca2t.firebasestorage.app',
    androidClientId: '71382402825-auia399ln4ee67o5vaca09beln22ib20.apps.googleusercontent.com',
    iosClientId: '71382402825-hpbe3da765mbqus9p3v5uaund13tutc3.apps.googleusercontent.com',
    iosBundleId: 'com.scanneranimal.app',
  );

}